### ISSUE TITLE
Versioned Control Unzipped Story Package

### ISSUE THREAD

**Issue by megazear7** [icfnext/storybook-aem#19]
Currently the version controlled package containing the stories is a zip file. This package can be updated based on changes made to the content in AEM. It can also be installed to AEM to update the stories in AEM based on changes in the code (for example when you pull down changes from another developer).

One issue is that zip files do not lend themselves well to version control. We could enhance this approach by version controlling the unzipped version of the package and only creating the zip package while installing the package to AEM.

To download the package from AEM into the codebase the cli will need to perform the following steps:
1. Download the package from AEM into the desired directory within the codebase as is already being done by the cli tool. We will call this the containing directory.
2. Run `rm -rf jcr_root`
3. Run `rm -rf META-INF`
4. Run `unzip stories.zip`
5. Run `rm stories.zip`

To install the package to AEM from the codebase run the following commands from the containing directory.
1. Run `zip -r stories.zip .`
2. Install stories.zip to AEM as is already being done.
3. Run `rm stories.zip`

It is important that the stories.zip is removed after both sets of steps otherwise it could get recursively nested into the package.

**Comment by megazear7** [comment]
This issue is being completed in [pull request 23](https://github.com/icfnext/storybook-aem/pull/23)

**Comment by jzeltman** [comment]
This issue has been addressed and closed.
